FROM php:8.2-fpm-alpine

WORKDIR /var/www/html

RUN apk add --no-cache \
    git \
    curl \
    libpng-dev \
    libzip-dev \
    oniguruma-dev \
    postgresql-dev \
    bash \
    && docker-php-ext-install \
       pdo \
       pdo_pgsql \
       mbstring \
       exif \
       pcntl \
       bcmath \
       gd \
       zip \
    && apk add --no-cache $PHPIZE_DEPS \
    && pecl install redis \
    && docker-php-ext-enable redis \
    && apk del $PHPIZE_DEPS

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Код монтируется томом в dev-режиме

EXPOSE 9000

CMD ["php-fpm"]









